// Base de datos oficial de los partidos y pronósticos - Quiniela Mundial 2026
// Partidos m1-m22: pronósticos pre-cargados por el administrador
// A partir de m23 (Ghana vs Panamá): cada participante ingresa su propio pronóstico

const INITIAL_MATCHES = [
  // Fechas almacenadas en UTC. El cÃ³digo las convierte a hora Caracas (UTC-4) automÃ¡ticamente.
  { id: "m1", apiId: 1, stage: "Fase de Grupos", group: "A", homeTeam: "México", awayTeam: "Sudáfrica", date: "2026-06-11 19:00", realHomeScore: 2, realAwayScore: 0, completed: true, status: "FINISHED" },
  { id: "m2", apiId: 2, stage: "Fase de Grupos", group: "A", homeTeam: "Corea del Sur", awayTeam: "Chequia", date: "2026-06-12 02:00", realHomeScore: 2, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m3", apiId: 3, stage: "Fase de Grupos", group: "B", homeTeam: "Canadá", awayTeam: "Bosnia y Herzegovina", date: "2026-06-12 19:00", realHomeScore: 1, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m4", apiId: 4, stage: "Fase de Grupos", group: "D", homeTeam: "EE.UU.", awayTeam: "Paraguay", date: "2026-06-13 01:00", realHomeScore: 4, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m5", apiId: 8, stage: "Fase de Grupos", group: "B", homeTeam: "Catar", awayTeam: "Suiza", date: "2026-06-13 19:00", realHomeScore: 1, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m6", apiId: 7, stage: "Fase de Grupos", group: "C", homeTeam: "Brasil", awayTeam: "Marruecos", date: "2026-06-13 22:00", realHomeScore: 1, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m7", apiId: 5, stage: "Fase de Grupos", group: "C", homeTeam: "Haití", awayTeam: "Escocia", date: "2026-06-14 01:00", realHomeScore: 0, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m8", apiId: 6, stage: "Fase de Grupos", group: "D", homeTeam: "Australia", awayTeam: "Turquía", date: "2026-06-14 04:00", realHomeScore: 2, realAwayScore: 0, completed: true, status: "FINISHED" },
  { id: "m9", apiId: 10, stage: "Fase de Grupos", group: "E", homeTeam: "Alemania", awayTeam: "Curaçao", date: "2026-06-14 17:00", realHomeScore: 7, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m10", apiId: 11, stage: "Fase de Grupos", group: "F", homeTeam: "Países Bajos", awayTeam: "Japón", date: "2026-06-14 20:00", realHomeScore: 2, realAwayScore: 2, completed: true, status: "FINISHED" },
  { id: "m11", apiId: 9, stage: "Fase de Grupos", group: "E", homeTeam: "Costa de Marfil", awayTeam: "Ecuador", date: "2026-06-14 23:00", realHomeScore: 1, realAwayScore: 0, completed: true, status: "FINISHED" },
  { id: "m12", apiId: 12, stage: "Fase de Grupos", group: "F", homeTeam: "Suecia", awayTeam: "Túnez", date: "2026-06-15 02:00", realHomeScore: 5, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m13", apiId: 14, stage: "Fase de Grupos", group: "H", homeTeam: "España", awayTeam: "Cabo Verde", date: "2026-06-15 16:00", realHomeScore: 0, realAwayScore: 0, completed: true, status: "FINISHED" },
  { id: "m14", apiId: 15, stage: "Fase de Grupos", group: "G", homeTeam: "Bélgica", awayTeam: "Egipto", date: "2026-06-15 19:00", realHomeScore: 1, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m15", apiId: 16, stage: "Fase de Grupos", group: "H", homeTeam: "Arabia Saudita", awayTeam: "Uruguay", date: "2026-06-15 22:00", realHomeScore: 1, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m16", apiId: 13, stage: "Fase de Grupos", group: "G", homeTeam: "Irán", awayTeam: "Nueva Zelanda", date: "2026-06-16 01:00", realHomeScore: 2, realAwayScore: 2, completed: true, status: "FINISHED" },
  { id: "m17", apiId: 17, stage: "Fase de Grupos", group: "I", homeTeam: "Francia", awayTeam: "Senegal", date: "2026-06-16 19:00", realHomeScore: 3, realAwayScore: 1, completed: true, status: "FINISHED" },
  { id: "m18", apiId: 18, stage: "Fase de Grupos", group: "I", homeTeam: "Irak", awayTeam: "Noruega", date: "2026-06-16 22:00", realHomeScore: 1, realAwayScore: 4, completed: true, status: "FINISHED" },
  { id: "m19", apiId: 19, stage: "Fase de Grupos", group: "J", homeTeam: "Argentina", awayTeam: "Argelia", date: "2026-06-17 01:00", realHomeScore: 3, realAwayScore: 0, completed: true, status: "FINISHED" },
  { id: "m20", apiId: 20, stage: "Fase de Grupos", group: "J", homeTeam: "Austria", awayTeam: "Jordania", date: "2026-06-17 04:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m21", apiId: 21, stage: "Fase de Grupos", group: "K", homeTeam: "Portugal", awayTeam: "RD Congo", date: "2026-06-17 17:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m22", apiId: 22, stage: "Fase de Grupos", group: "L", homeTeam: "Inglaterra", awayTeam: "Croacia", date: "2026-06-17 20:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m23", apiId: 24, stage: "Fase de Grupos", group: "L", homeTeam: "Ghana", awayTeam: "Panamá", date: "2026-06-17 23:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m24", apiId: 23, stage: "Fase de Grupos", group: "K", homeTeam: "Uzbekistán", awayTeam: "Colombia", date: "2026-06-18 02:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m25", apiId: 28, stage: "Fase de Grupos", group: "A", homeTeam: "Chequia", awayTeam: "Sudáfrica", date: "2026-06-18 16:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m26", apiId: 26, stage: "Fase de Grupos", group: "B", homeTeam: "Suiza", awayTeam: "Bosnia y Herzegovina", date: "2026-06-18 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m27", apiId: 27, stage: "Fase de Grupos", group: "B", homeTeam: "Canadá", awayTeam: "Catar", date: "2026-06-18 22:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m28", apiId: 25, stage: "Fase de Grupos", group: "A", homeTeam: "México", awayTeam: "Corea del Sur", date: "2026-06-19 01:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m29", apiId: 31, stage: "Fase de Grupos", group: "D", homeTeam: "EE.UU.", awayTeam: "Australia", date: "2026-06-19 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m30", apiId: 30, stage: "Fase de Grupos", group: "C", homeTeam: "Escocia", awayTeam: "Marruecos", date: "2026-06-19 22:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m31", apiId: 29, stage: "Fase de Grupos", group: "C", homeTeam: "Brasil", awayTeam: "Haití", date: "2026-06-20 01:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m32", apiId: 32, stage: "Fase de Grupos", group: "D", homeTeam: "Turquía", awayTeam: "Paraguay", date: "2026-06-20 03:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m33", apiId: 35, stage: "Fase de Grupos", group: "F", homeTeam: "Países Bajos", awayTeam: "Suecia", date: "2026-06-20 17:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m34", apiId: 33, stage: "Fase de Grupos", group: "E", homeTeam: "Alemania", awayTeam: "Costa de Marfil", date: "2026-06-20 20:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m35", apiId: 34, stage: "Fase de Grupos", group: "E", homeTeam: "Ecuador", awayTeam: "Curaçao", date: "2026-06-21 00:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m36", apiId: 36, stage: "Fase de Grupos", group: "F", homeTeam: "Túnez", awayTeam: "Japón", date: "2026-06-21 04:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m37", apiId: 39, stage: "Fase de Grupos", group: "H", homeTeam: "España", awayTeam: "Arabia Saudita", date: "2026-06-21 16:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m38", apiId: 37, stage: "Fase de Grupos", group: "G", homeTeam: "Bélgica", awayTeam: "Irán", date: "2026-06-21 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m39", apiId: 40, stage: "Fase de Grupos", group: "H", homeTeam: "Uruguay", awayTeam: "Cabo Verde", date: "2026-06-21 22:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m40", apiId: 38, stage: "Fase de Grupos", group: "G", homeTeam: "Nueva Zelanda", awayTeam: "Egipto", date: "2026-06-22 01:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m41", apiId: 43, stage: "Fase de Grupos", group: "J", homeTeam: "Argentina", awayTeam: "Austria", date: "2026-06-22 17:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m42", apiId: 41, stage: "Fase de Grupos", group: "I", homeTeam: "Francia", awayTeam: "Irak", date: "2026-06-22 21:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m43", apiId: 42, stage: "Fase de Grupos", group: "I", homeTeam: "Noruega", awayTeam: "Senegal", date: "2026-06-23 00:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m44", apiId: 44, stage: "Fase de Grupos", group: "J", homeTeam: "Jordania", awayTeam: "Argelia", date: "2026-06-23 03:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m45", apiId: 45, stage: "Fase de Grupos", group: "K", homeTeam: "Portugal", awayTeam: "Uzbekistán", date: "2026-06-23 17:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m46", apiId: 48, stage: "Fase de Grupos", group: "L", homeTeam: "Inglaterra", awayTeam: "Ghana", date: "2026-06-23 20:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m47", apiId: 46, stage: "Fase de Grupos", group: "L", homeTeam: "Panamá", awayTeam: "Croacia", date: "2026-06-23 23:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m48", apiId: 47, stage: "Fase de Grupos", group: "K", homeTeam: "Colombia", awayTeam: "RD Congo", date: "2026-06-24 02:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m49", apiId: 53, stage: "Fase de Grupos", group: "B", homeTeam: "Bosnia y Herzegovina", awayTeam: "Catar", date: "2026-06-24 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m50", apiId: 54, stage: "Fase de Grupos", group: "B", homeTeam: "Suiza", awayTeam: "Canadá", date: "2026-06-24 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m51", apiId: 49, stage: "Fase de Grupos", group: "C", homeTeam: "Escocia", awayTeam: "Brasil", date: "2026-06-24 22:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m52", apiId: 50, stage: "Fase de Grupos", group: "C", homeTeam: "Marruecos", awayTeam: "Haití", date: "2026-06-24 22:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m53", apiId: 51, stage: "Fase de Grupos", group: "A", homeTeam: "Sudáfrica", awayTeam: "Corea del Sur", date: "2026-06-25 01:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m54", apiId: 52, stage: "Fase de Grupos", group: "A", homeTeam: "Chequia", awayTeam: "México", date: "2026-06-25 01:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m55", apiId: 55, stage: "Fase de Grupos", group: "E", homeTeam: "Curaçao", awayTeam: "Costa de Marfil", date: "2026-06-25 20:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m56", apiId: 56, stage: "Fase de Grupos", group: "E", homeTeam: "Ecuador", awayTeam: "Alemania", date: "2026-06-25 20:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m57", apiId: 59, stage: "Fase de Grupos", group: "F", homeTeam: "Japón", awayTeam: "Suecia", date: "2026-06-25 23:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m58", apiId: 60, stage: "Fase de Grupos", group: "F", homeTeam: "Túnez", awayTeam: "Países Bajos", date: "2026-06-25 23:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m59", apiId: 57, stage: "Fase de Grupos", group: "D", homeTeam: "Paraguay", awayTeam: "Australia", date: "2026-06-26 02:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m60", apiId: 58, stage: "Fase de Grupos", group: "D", homeTeam: "Turquía", awayTeam: "EE.UU.", date: "2026-06-26 02:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m61", apiId: 61, stage: "Fase de Grupos", group: "I", homeTeam: "Senegal", awayTeam: "Irak", date: "2026-06-26 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m62", apiId: 62, stage: "Fase de Grupos", group: "I", homeTeam: "Noruega", awayTeam: "Francia", date: "2026-06-26 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m63", apiId: 65, stage: "Fase de Grupos", group: "H", homeTeam: "Cabo Verde", awayTeam: "Arabia Saudita", date: "2026-06-27 00:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m64", apiId: 66, stage: "Fase de Grupos", group: "H", homeTeam: "Uruguay", awayTeam: "España", date: "2026-06-27 00:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m65", apiId: 63, stage: "Fase de Grupos", group: "G", homeTeam: "Egipto", awayTeam: "Irán", date: "2026-06-27 03:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m66", apiId: 64, stage: "Fase de Grupos", group: "G", homeTeam: "Nueva Zelanda", awayTeam: "Bélgica", date: "2026-06-27 03:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m67", apiId: 67, stage: "Fase de Grupos", group: "L", homeTeam: "Panamá", awayTeam: "Inglaterra", date: "2026-06-27 21:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m68", apiId: 68, stage: "Fase de Grupos", group: "L", homeTeam: "Croacia", awayTeam: "Ghana", date: "2026-06-27 21:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m69", apiId: 71, stage: "Fase de Grupos", group: "K", homeTeam: "Colombia", awayTeam: "Portugal", date: "2026-06-27 23:30", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m70", apiId: 72, stage: "Fase de Grupos", group: "K", homeTeam: "RD Congo", awayTeam: "Uzbekistán", date: "2026-06-27 23:30", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m71", apiId: 69, stage: "Fase de Grupos", group: "J", homeTeam: "Argelia", awayTeam: "Austria", date: "2026-06-28 02:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m72", apiId: 70, stage: "Fase de Grupos", group: "J", homeTeam: "Jordania", awayTeam: "Argentina", date: "2026-06-28 02:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m73", apiId: 73, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Segundo Grupo A", awayTeam: "Segundo Grupo B", date: "2026-06-28 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m74", apiId: 76, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo C", awayTeam: "Segundo Grupo F", date: "2026-06-29 17:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m75", apiId: 74, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo E", awayTeam: "3ro Grupo A/B/C/D/F", date: "2026-06-29 20:30", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m76", apiId: 75, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo F", awayTeam: "Segundo Grupo C", date: "2026-06-30 01:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m77", apiId: 78, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Segundo Grupo E", awayTeam: "Segundo Grupo I", date: "2026-06-30 17:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m78", apiId: 77, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo I", awayTeam: "3ro Grupo C/D/F/G/H", date: "2026-06-30 21:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m79", apiId: 79, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo A", awayTeam: "3ro Grupo C/E/F/H/I", date: "2026-07-01 01:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m80", apiId: 80, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo L", awayTeam: "3ro Grupo E/H/I/J/K", date: "2026-07-01 16:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m81", apiId: 82, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo G", awayTeam: "3ro Grupo A/E/H/I/J", date: "2026-07-01 20:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m82", apiId: 81, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo D", awayTeam: "3ro Grupo B/E/F/I/J", date: "2026-07-02 00:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m83", apiId: 84, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo H", awayTeam: "Segundo Grupo J", date: "2026-07-02 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m84", apiId: 83, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Segundo Grupo K", awayTeam: "Segundo Grupo L", date: "2026-07-02 23:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m85", apiId: 85, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo B", awayTeam: "3ro Grupo E/F/G/I/J", date: "2026-07-03 03:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m86", apiId: 88, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Segundo Grupo D", awayTeam: "Segundo Grupo G", date: "2026-07-03 18:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m87", apiId: 86, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo J", awayTeam: "Segundo Grupo H", date: "2026-07-03 22:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m88", apiId: 87, stage: "Dieciseisavos de Final", group: "R32", homeTeam: "Ganador Grupo K", awayTeam: "3ro Grupo D/E/I/J/L", date: "2026-07-04 01:30", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m89", apiId: 90, stage: "Octavos de Final", group: "R16", homeTeam: "Ganador Partido 73", awayTeam: "Ganador Partido 75", date: "2026-07-04 17:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m90", apiId: 89, stage: "Octavos de Final", group: "R16", homeTeam: "Ganador Partido 74", awayTeam: "Ganador Partido 77", date: "2026-07-04 21:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m91", apiId: 91, stage: "Octavos de Final", group: "R16", homeTeam: "Ganador Partido 76", awayTeam: "Ganador Partido 78", date: "2026-07-05 20:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m92", apiId: 92, stage: "Octavos de Final", group: "R16", homeTeam: "Ganador Partido 79", awayTeam: "Ganador Partido 80", date: "2026-07-06 00:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m93", apiId: 93, stage: "Octavos de Final", group: "R16", homeTeam: "Ganador Partido 83", awayTeam: "Ganador Partido 84", date: "2026-07-06 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m94", apiId: 94, stage: "Octavos de Final", group: "R16", homeTeam: "Ganador Partido 81", awayTeam: "Ganador Partido 82", date: "2026-07-07 00:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m95", apiId: 95, stage: "Octavos de Final", group: "R16", homeTeam: "Ganador Partido 86", awayTeam: "Ganador Partido 88", date: "2026-07-07 16:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m96", apiId: 96, stage: "Octavos de Final", group: "R16", homeTeam: "Ganador Partido 85", awayTeam: "Ganador Partido 87", date: "2026-07-07 20:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m97", apiId: 97, stage: "Cuartos de Final", group: "QF", homeTeam: "Ganador Partido 89", awayTeam: "Ganador Partido 90", date: "2026-07-09 20:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m98", apiId: 98, stage: "Cuartos de Final", group: "QF", homeTeam: "Ganador Partido 93", awayTeam: "Ganador Partido 94", date: "2026-07-10 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m99", apiId: 99, stage: "Cuartos de Final", group: "QF", homeTeam: "Ganador Partido 91", awayTeam: "Ganador Partido 92", date: "2026-07-11 21:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m100", apiId: 100, stage: "Cuartos de Final", group: "QF", homeTeam: "Ganador Partido 95", awayTeam: "Ganador Partido 96", date: "2026-07-12 01:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m101", apiId: 101, stage: "Semifinales", group: "SF", homeTeam: "Ganador Partido 97", awayTeam: "Ganador Partido 98", date: "2026-07-14 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m102", apiId: 102, stage: "Semifinales", group: "SF", homeTeam: "Ganador Partido 99", awayTeam: "Ganador Partido 100", date: "2026-07-15 19:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m103", apiId: 103, stage: "Tercer Puesto", group: "3RD", homeTeam: "Perdedor Partido 101", awayTeam: "Perdedor Partido 102", date: "2026-07-18 21:00", realHomeScore: null, realAwayScore: null, completed: false },
  { id: "m104", apiId: 104, stage: "Final", group: "FINAL", homeTeam: "Ganador Partido 101", awayTeam: "Ganador Partido 102", date: "2026-07-19 19:00", realHomeScore: null, realAwayScore: null, completed: false },
];


// Usuarios Iniciales del Tablero (sin PIN para que se registren ellos mismos)
const INITIAL_USERS = [
  { id: "angel", name: "Ángel Borjas", pin: null, avatar: "🦁" },
  { id: "jairo", name: "Jairo Gutiérrez", pin: null, avatar: "🏆" },
  { id: "jesus", name: "Jesús Sánchez", pin: null, avatar: "🔥" },
  { id: "anabell", name: "Anabell Peña", pin: null, avatar: "🌟" },
  { id: "luis", name: "Luis Rivas", pin: null, avatar: "🦖" },
  { id: "nicolas", name: "Nicolás Peña", pin: null, avatar: "⚡" },
  { id: "yein", name: "Yein Azócar", pin: null, avatar: "😎" },
  { id: "jonathan", name: "Jonathan Calderón", pin: null, avatar: "⚽" }
];

// Pronósticos oficiales vaciados
const INITIAL_PREDICTIONS = {
  // Partido 1: México vs Sudáfrica
  "angel_m1": { homeScore: 1, awayScore: 1 },
  "jairo_m1": { homeScore: 2, awayScore: 1 },
  "jesus_m1": { homeScore: 2, awayScore: 0 },
  "anabell_m1": { homeScore: 0, awayScore: 0 },
  "luis_m1": { homeScore: 2, awayScore: 0 },
  "nicolas_m1": { homeScore: 2, awayScore: 0 },
  "yein_m1": { homeScore: 2, awayScore: 0 },

  // Partido 2: Corea del Sur vs Chequia
  "angel_m2": { homeScore: 1, awayScore: 0 },
  "jairo_m2": { homeScore: 1, awayScore: 0 },
  "jesus_m2": { homeScore: 0, awayScore: 3 },
  // anabell_m2 no tiene pronóstico
  "luis_m2": { homeScore: 1, awayScore: 0 },
  "nicolas_m2": { homeScore: 0, awayScore: 0 },
  "yein_m2": { homeScore: 1, awayScore: 0 },

  // Partido 3: Canadá vs Bosnia y Herzegovina
  "angel_m3": { homeScore: 1, awayScore: 0 },
  "jairo_m3": { homeScore: 2, awayScore: 0 },
  "jesus_m3": { homeScore: 0, awayScore: 2 },
  "anabell_m3": { homeScore: 1, awayScore: 0 },
  "luis_m3": { homeScore: 1, awayScore: 1 },
  "nicolas_m3": { homeScore: 1, awayScore: 0 },
  "yein_m3": { homeScore: 2, awayScore: 0 },

  // Partido 4: EE.UU. vs Paraguay
  "angel_m4": { homeScore: 1, awayScore: 2 },
  "jairo_m4": { homeScore: 2, awayScore: 1 },
  "jesus_m4": { homeScore: 2, awayScore: 0 },
  "anabell_m4": { homeScore: 2, awayScore: 1 },
  "luis_m4": { homeScore: 1, awayScore: 2 },
  "nicolas_m4": { homeScore: 2, awayScore: 2 },
  "yein_m4": { homeScore: 2, awayScore: 1 },

  // Partido 5: Catar vs Suiza
  "angel_m5": { homeScore: 1, awayScore: 2 },
  "jairo_m5": { homeScore: 0, awayScore: 2 },
  "jesus_m5": { homeScore: 0, awayScore: 1 },
  "anabell_m5": { homeScore: 0, awayScore: 2 },
  "luis_m5": { homeScore: 0, awayScore: 2 },
  "nicolas_m5": { homeScore: 1, awayScore: 2 },
  "yein_m5": { homeScore: 0, awayScore: 2 },

  // Partido 6: Brasil vs Marruecos
  "angel_m6": { homeScore: 3, awayScore: 1 },
  "jairo_m6": { homeScore: 3, awayScore: 2 },
  "jesus_m6": { homeScore: 2, awayScore: 0 },
  "anabell_m6": { homeScore: 3, awayScore: 1 },
  "luis_m6": { homeScore: 2, awayScore: 2 },
  "nicolas_m6": { homeScore: 3, awayScore: 2 },
  "yein_m6": { homeScore: 2, awayScore: 1 },

  // Partido 7: Haití vs Escocia
  "angel_m7": { homeScore: 0, awayScore: 2 },
  "jairo_m7": { homeScore: 0, awayScore: 2 },
  "jesus_m7": { homeScore: 0, awayScore: 3 },
  "anabell_m7": { homeScore: 1, awayScore: 1 },
  "luis_m7": { homeScore: 0, awayScore: 2 },
  "nicolas_m7": { homeScore: 1, awayScore: 2 },
  "yein_m7": { homeScore: 0, awayScore: 2 },

  // Partido 8: Australia vs Turquía
  "angel_m8": { homeScore: 0, awayScore: 2 },
  "jairo_m8": { homeScore: 1, awayScore: 2 },
  "jesus_m8": { homeScore: 1, awayScore: 1 },
  "anabell_m8": { homeScore: 1, awayScore: 2 },
  "luis_m8": { homeScore: 1, awayScore: 2 },
  "nicolas_m8": { homeScore: 1, awayScore: 2 },
  "yein_m8": { homeScore: 1, awayScore: 1 },

  // Partido 9: Alemania vs Curazao
  "angel_m9": { homeScore: 3, awayScore: 0 },
  "jairo_m9": { homeScore: 3, awayScore: 0 },
  "jesus_m9": { homeScore: 5, awayScore: 0 },
  "anabell_m9": { homeScore: 3, awayScore: 1 },
  "luis_m9": { homeScore: 3, awayScore: 0 },
  "nicolas_m9": { homeScore: 4, awayScore: 0 },
  "yein_m9": { homeScore: 4, awayScore: 0 },

  // Partido 10: Países Bajos vs Japón
  "angel_m10": { homeScore: 1, awayScore: 2 },
  "jairo_m10": { homeScore: 2, awayScore: 2 },
  "jesus_m10": { homeScore: 3, awayScore: 0 },
  "anabell_m10": { homeScore: 1, awayScore: 1 },
  "luis_m10": { homeScore: 2, awayScore: 1 },
  "nicolas_m10": { homeScore: 1, awayScore: 2 },
  "yein_m10": { homeScore: 2, awayScore: 0 },

  // Partido 11: Costa de Marfil vs Ecuador
  "angel_m11": { homeScore: 1, awayScore: 1 },
  "jairo_m11": { homeScore: 1, awayScore: 2 },
  "jesus_m11": { homeScore: 0, awayScore: 2 },
  "anabell_m11": { homeScore: 1, awayScore: 1 },
  "luis_m11": { homeScore: 1, awayScore: 1 },
  "nicolas_m11": { homeScore: 0, awayScore: 2 },
  "yein_m11": { homeScore: 0, awayScore: 1 },

  // Partido 12: Suecia vs Túnez
  "angel_m12": { homeScore: 1, awayScore: 0 },
  "jairo_m12": { homeScore: 2, awayScore: 0 },
  "jesus_m12": { homeScore: 2, awayScore: 0 },
  "anabell_m12": { homeScore: 2, awayScore: 1 },
  "luis_m12": { homeScore: 1, awayScore: 0 },
  "nicolas_m12": { homeScore: 1, awayScore: 1 },
  "yein_m12": { homeScore: 2, awayScore: 0 },

  // Partido 13: España vs Cabo Verde
  "angel_m13": { homeScore: 4, awayScore: 0 },
  "jairo_m13": { homeScore: 3, awayScore: 1 },
  "jesus_m13": { homeScore: 5, awayScore: 0 },
  "anabell_m13": { homeScore: 3, awayScore: 0 },
  "luis_m13": { homeScore: 3, awayScore: 0 },
  "nicolas_m13": { homeScore: 3, awayScore: 0 },
  "yein_m13": { homeScore: 3, awayScore: 0 },

  // Partido 14: Bélgica vs Egipto
  "angel_m14": { homeScore: 2, awayScore: 1 },
  "jairo_m14": { homeScore: 2, awayScore: 0 },
  "jesus_m14": { homeScore: 3, awayScore: 0 },
  "anabell_m14": { homeScore: 2, awayScore: 0 },
  "luis_m14": { homeScore: 2, awayScore: 0 },
  "nicolas_m14": { homeScore: 2, awayScore: 0 },
  "yein_m14": { homeScore: 2, awayScore: 1 },
  "jonathan_m14": { homeScore: 2, awayScore: 2 },

  // Partido 15: Arabia Saudita vs Uruguay
  "angel_m15": { homeScore: 0, awayScore: 2 },
  "jairo_m15": { homeScore: 1, awayScore: 2 },
  "jesus_m15": { homeScore: 1, awayScore: 3 },
  "anabell_m15": { homeScore: 0, awayScore: 1 },
  "luis_m15": { homeScore: 0, awayScore: 2 },
  "nicolas_m15": { homeScore: 0, awayScore: 2 },
  "yein_m15": { homeScore: 0, awayScore: 2 },
  "jonathan_m15": { homeScore: 0, awayScore: 2 },

  // Partido 16: Irán vs Nueva Zelanda
  "angel_m16": { homeScore: 0, awayScore: 2 },
  "jairo_m16": { homeScore: 1, awayScore: 2 },
  "jesus_m16": { homeScore: 1, awayScore: 1 },
  "anabell_m16": { homeScore: 0, awayScore: 1 },
  "luis_m16": { homeScore: 0, awayScore: 1 },
  "nicolas_m16": { homeScore: 1, awayScore: 1 },
  "yein_m16": { homeScore: 0, awayScore: 1 },
  "jonathan_m16": { homeScore: 1, awayScore: 0 },

  // Partido 17: Francia vs Senegal
  "angel_m17": { homeScore: 3, awayScore: 0 },
  "jairo_m17": { homeScore: 3, awayScore: 1 },
  "jesus_m17": { homeScore: 3, awayScore: 0 },
  "anabell_m17": { homeScore: 2, awayScore: 0 },
  "luis_m17": { homeScore: 2, awayScore: 1 },
  "nicolas_m17": { homeScore: 3, awayScore: 1 },
  "yein_m17": { homeScore: 2, awayScore: 1 },
  "jonathan_m17": { homeScore: 2, awayScore: 1 },

  // Partido 18: Irak vs Noruega
  "angel_m18": { homeScore: 1, awayScore: 2 },
  "jairo_m18": { homeScore: 0, awayScore: 2 },
  "jesus_m18": { homeScore: 1, awayScore: 2 },
  "anabell_m18": { homeScore: 0, awayScore: 0 },
  "luis_m18": { homeScore: 1, awayScore: 2 },
  "nicolas_m18": { homeScore: 1, awayScore: 3 },
  "yein_m18": { homeScore: 0, awayScore: 2 },
  "jonathan_m18": { homeScore: 0, awayScore: 3 },

  // Partido 19: Argentina vs Argelia
  "angel_m19": { homeScore: 3, awayScore: 0 },
  "jairo_m19": { homeScore: 2, awayScore: 1 },
  "jesus_m19": { homeScore: 2, awayScore: 0 },
  "anabell_m19": { homeScore: 3, awayScore: 1 },
  "luis_m19": { homeScore: 2, awayScore: 0 },
  "nicolas_m19": { homeScore: 2, awayScore: 0 },
  "yein_m19": { homeScore: 2, awayScore: 0 },
  "jonathan_m19": { homeScore: 1, awayScore: 1 },

  // Partido 20: Austria vs Jordania
  "angel_m20": { homeScore: 1, awayScore: 1 },
  "jairo_m20": { homeScore: 1, awayScore: 0 },
  "jesus_m20": { homeScore: 1, awayScore: 0 },
  "anabell_m20": { homeScore: 1, awayScore: 0 },
  "luis_m20": { homeScore: 1, awayScore: 1 },
  "nicolas_m20": { homeScore: 2, awayScore: 1 },
  "yein_m20": { homeScore: 2, awayScore: 0 },
  "jonathan_m20": { homeScore: 2, awayScore: 0 },

  // Partido 21: Portugal vs RD Congo
  "angel_m21": { homeScore: 3, awayScore: 0 },
  "jairo_m21": { homeScore: 3, awayScore: 0 },
  "jesus_m21": { homeScore: 2, awayScore: 0 },
  "anabell_m21": { homeScore: 2, awayScore: 0 },
  "luis_m21": { homeScore: 2, awayScore: 0 },
  "nicolas_m21": { homeScore: 2, awayScore: 0 },
  "yein_m21": { homeScore: 3, awayScore: 0 },
  "jonathan_m21": { homeScore: 3, awayScore: 0 },

  // Partido 22: Inglaterra vs Croacia
  "angel_m22": { homeScore: 3, awayScore: 2 },
  "jairo_m22": { homeScore: 3, awayScore: 2 },
  "jesus_m22": { homeScore: 2, awayScore: 1 },
  "anabell_m22": { homeScore: 2, awayScore: 0 },
  "luis_m22": { homeScore: 2, awayScore: 2 },
  "nicolas_m22": { homeScore: 3, awayScore: 1 },
  "yein_m22": { homeScore: 2, awayScore: 1 },
  "jonathan_m22": { homeScore: 1, awayScore: 2 }
};

module.exports = { INITIAL_MATCHES, INITIAL_USERS, INITIAL_PREDICTIONS };
